version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - run: exit 1
  report:
    executor: node/default
    steps:
      - checkout
      - run: exit 0


workflows:
  test_report: # this can be any name you choose
    jobs:
        - test
        - report:
            requires: 
              - test
